---
title: "SDS 192 Mini-Project 3 and 4 Standards"
subtitle: "SDS 192"
author: 
- name: Author One
  affiliation: Smith College
- name: Author Two
  affiliation: Smith College
- name: Author Three
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---

# Pivoting Data

Fill response here...

# Joining Data

Fill response here...

# Acquiring API Data

Fill response here...

# Point Mapping

Fill response here...

# Polygon Mapping

Fill response here...

# Optional

## Tracing Data Provenance 

Fill response here...

## Data Fundamentals

Fill response here...

## Univariate Plotting

Fill response here...

## Visualization Aesthetics

Fill response here...

## Visualization Context 

Fill response here...

## Multivariate Plotting

Fill response here...

## Error Resolution and Problem-Solving

Fill response here...

## GitHub

Everyone that submits an assignment will get credit for this!

## RMarkdown

Fill response here..

## Subsetting Data

Fill response here..

## Aggregating Data

Fill response here..

## Importing Data

Fill response here..

## Code Styling

Fill response here..

## Cleaning Data

Fill response here..


